index:
    path: /
    controller: App\Controller\HomeController::index

list:
    path: /api/projects
    controller: App\Controller\ProjectController::index

filter:
    path: /api/projects/filter
    controller: App\Controller\ProjectController::filter
    methods: [POST]

detail:
    path: /api/projects/{id}
    controller: App\Controller\ProjectController::viewProject
